[project]
name = "ap_agent_api"
version = "0.1.0"
dependencies=[
    "openai-agents==0.6.1",
    "coloredlogs==15.0.1",
    "fastapi==0.104.1",
    "uvicorn[standard]==0.24.0",
    "pydantic==2.5.0"
]

[tool.setuptools.packages.find]
where = ["src"]